version: 0.0
os: os-name
files: #source-destination-files-mappings
    - source: /
    destination: /home/ec2-user/
permissions: # permissions-specifications
  - object: /tmp/my-app
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755
hooks: # deployment-lifecycle-event-mappings
  ApplicationStart:
    - location: start.sh
      timeout: 100
      runas: ec2-user
  ApplicationStop:
    - location: stop.sh
      timeout: 100
      runas: ec2-user
